import type { Market } from './types'

export const luxembourgMarket: Market = {
  id: 'lu',
  name: 'Luxembourg',
  countryCode: 'LU',
  supportedLanguages: ['de', 'fr', 'en', 'lu'],
  propertyTypes: ['apartment', 'house', 'penthouse', 'studio', 'duplex', 'villa'],
  features: [
    'balcony',
    'parking',
    'garden',
    'elevator',
    'storage',
    'pool',
    'terrace',
    'furnished',
    'new-build',
    'renovated',
    'city-view',
  ],
  areas: [
    {
      id: 'luxembourg-city',
      name: 'Luxembourg City',
      defaultCurrency: 'EUR',
      locale: 'fr-LU',
      areaUnit: 'sqm',
      neighborhoods: [
        {
          id: 'kirchberg',
          name: 'Kirchberg',
          slug: 'kirchberg',
          pricePerSqm: { min: 8500, max: 14000, median: 11000, currency: 'EUR' },
          tags: ['EU quarter', 'modern', 'expat-friendly', 'business district'],
        },
        {
          id: 'belair',
          name: 'Belair',
          slug: 'belair',
          pricePerSqm: { min: 8000, max: 13000, median: 10500, currency: 'EUR' },
          tags: ['residential', 'upscale', 'green', 'family-friendly'],
        },
        {
          id: 'limpertsberg',
          name: 'Limpertsberg',
          slug: 'limpertsberg',
          pricePerSqm: { min: 7500, max: 12500, median: 10000, currency: 'EUR' },
          tags: ['university area', 'cultural', 'parks', 'sought-after'],
        },
        {
          id: 'merl',
          name: 'Merl',
          slug: 'merl',
          pricePerSqm: { min: 7000, max: 12000, median: 9500, currency: 'EUR' },
          tags: ['quiet', 'residential', 'green', 'family-friendly'],
        },
        {
          id: 'hollerich',
          name: 'Hollerich',
          slug: 'hollerich',
          pricePerSqm: { min: 6000, max: 10000, median: 8000, currency: 'EUR' },
          tags: ['up-and-coming', 'creative district', 'central', 'urban'],
        },
        {
          id: 'bonnevoie',
          name: 'Bonnevoie',
          slug: 'bonnevoie',
          pricePerSqm: { min: 5500, max: 9500, median: 7500, currency: 'EUR' },
          tags: ['multicultural', 'lively', 'affordable', 'central'],
        },
        {
          id: 'centre-ville',
          name: 'Centre-Ville',
          slug: 'centre-ville',
          pricePerSqm: { min: 9000, max: 15000, median: 12000, currency: 'EUR' },
          tags: ['city center', 'historic', 'premium', 'walkable'],
        },
        {
          id: 'strassen',
          name: 'Strassen',
          slug: 'strassen',
          pricePerSqm: { min: 6500, max: 10500, median: 8500, currency: 'EUR' },
          tags: ['suburban', 'family-friendly', 'good schools', 'accessible'],
        },
        {
          id: 'esch-sur-alzette',
          name: 'Esch-sur-Alzette',
          slug: 'esch-sur-alzette',
          pricePerSqm: { min: 4500, max: 8000, median: 6000, currency: 'EUR' },
          tags: ['second city', 'affordable', 'multicultural', 'growing'],
        },
        {
          id: 'cloche-dor',
          name: 'Cloche d\'Or',
          slug: 'cloche-dor',
          pricePerSqm: { min: 8000, max: 13500, median: 10800, currency: 'EUR' },
          tags: ['new development', 'modern', 'business hub', 'amenities'],
        },
      ],
    },
  ],
}
